### ISSUE TITLE
作为特征提取器

### ISSUE THREAD

**Issue by AlexNmSED** [qiaoyu-zheng/RP3D-Diag#3]
您是否可以提供RP3D-Diag作为特征提取器的应用代码？或者说简要的介绍

**Comment by qiaoyu-zheng** [comment]
https://github.com/qiaoyu-zheng/RP3D-Diag/blob/main/src/Train/Model/resAttention.py 你可以参考这个文件，主要思想就是将3D图像的每一个slice都当作一个2D图，然后再利用transformer encoder的结构将slices的特征融合起来

**Comment by AlexNmSED** [comment]
好的，感谢您的信息。我康康

**Comment by AlexNmSED** [comment]
好的，感谢您的信息，这个我看过了。我主要是不清楚如何利用你们的预训练模型提取3D图像的每一个slice的特征，不知道可以参考那个文件。

**Comment by qiaoyu-zheng** [comment]
在https://github.com/qiaoyu-zheng/RP3D-Diag/blob/main/RP3D_Demo/Model/modelRadNet.py 的RadNet类中，你可以找到这段代码，它就是提取每一个slice的特征并将slices的特征融合
if self.backbone == 'resnet':
                output = self.resnet2D(image_x)
                output_x= output["x"]

            output_x = rearrange(output_x, '(B d) h -> B d h', B=Bs)
            output_x, attn_x, score_x = self.attention1D(output_x, marks)

**Comment by AlexNmSED** [comment]
我理解了，在modelRadNet.py 中，你们是用：pretrained resnet 作为了每个slice的特征提取器然后训练的。

`if self.backbone == 'resnet':
            self.resnet2D = resnet50_2D(weights=("pretrained", ResNet50_Weights.DEFAULT))
            # self.resnet2D = resnet34_2D(weights=("pretrained", ResNet34_Weights.DEFAULT))
            self.attention1D = Attention1D(hid_dim=hid_dim, max_depth=depth, nhead=1, num_layers=1, pool='cls', batch_first=True)`

我看到 在 RadFM 这个项目里，提到可以用 这个大模型 作为特征提取器：

![1724938931098](https://github.com/user-attachments/assets/1b12b90c-21bd-49d4-b161-49619ba598ab)
